// Hyper guest-agent gRPC interface.
//
// This contract is spoken over a virtio-vsock channel between the host and the
// Firecracker guest. The guest binds a tonic server on vsock port 1024
// (`VSOCK_PORT` in native/guest-agent/src/main.rs); the host reaches it through
// the per-VM relay, which performs the `CONNECT 1024` handshake (`@vsock_port`
// in lib/hyper/node/fire_vmm/agent/relay.ex). Those two literals must agree.
//
// Versioning: this is `v1`. The service is internal to hyper; the contract may
// change between releases. Pin to a specific commit if you depend on it.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: agent.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GuestAgent_Exec_FullMethodName   = "/hyper.agent.v1.GuestAgent/Exec"
	GuestAgent_Health_FullMethodName = "/hyper.agent.v1.GuestAgent/Health"
)

// GuestAgentClient is the client API for GuestAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Guest-agent service: executes commands inside the VM and reports liveness.
type GuestAgentClient interface {
	// Run a command inside the guest and return its exit code and captured output.
	Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error)
	// Check whether the guest agent is alive and ready to accept commands.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type guestAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewGuestAgentClient(cc grpc.ClientConnInterface) GuestAgentClient {
	return &guestAgentClient{cc}
}

func (c *guestAgentClient) Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecResponse)
	err := c.cc.Invoke(ctx, GuestAgent_Exec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guestAgentClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, GuestAgent_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GuestAgentServer is the server API for GuestAgent service.
// All implementations must embed UnimplementedGuestAgentServer
// for forward compatibility.
//
// Guest-agent service: executes commands inside the VM and reports liveness.
type GuestAgentServer interface {
	// Run a command inside the guest and return its exit code and captured output.
	Exec(context.Context, *ExecRequest) (*ExecResponse, error)
	// Check whether the guest agent is alive and ready to accept commands.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedGuestAgentServer()
}

// UnimplementedGuestAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGuestAgentServer struct{}

func (UnimplementedGuestAgentServer) Exec(context.Context, *ExecRequest) (*ExecResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedGuestAgentServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedGuestAgentServer) mustEmbedUnimplementedGuestAgentServer() {}
func (UnimplementedGuestAgentServer) testEmbeddedByValue()                    {}

// UnsafeGuestAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GuestAgentServer will
// result in compilation errors.
type UnsafeGuestAgentServer interface {
	mustEmbedUnimplementedGuestAgentServer()
}

func RegisterGuestAgentServer(s grpc.ServiceRegistrar, srv GuestAgentServer) {
	// If the following call panics, it indicates UnimplementedGuestAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GuestAgent_ServiceDesc, srv)
}

func _GuestAgent_Exec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuestAgentServer).Exec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuestAgent_Exec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuestAgentServer).Exec(ctx, req.(*ExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuestAgent_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuestAgentServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuestAgent_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuestAgentServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GuestAgent_ServiceDesc is the grpc.ServiceDesc for GuestAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GuestAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hyper.agent.v1.GuestAgent",
	HandlerType: (*GuestAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Exec",
			Handler:    _GuestAgent_Exec_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _GuestAgent_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent.proto",
}
