// Hyper -- public gRPC interface to a Hyper cluster.
//
// Hyper is a distributed orchestrator for Firecracker microVMs. This file is
// the language-agnostic contract for driving it: creating, stopping, locating,
// and listing microVMs ("VMs") from any gRPC client.
//
// A VM is addressed by its `vm_id` -- a URL-safe base64 string the server mints
// at creation. Placement across the cluster is automatic; the server is
// stateless and identical on every node, so any node can serve any request.
//
// Versioning: this is `v0` and UNSTABLE. The contract may change without notice
// during early development. Pin to a specific commit if you depend on it.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: hyper.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A fixed (vCPU, memory, disk) size, like a cloud instance class. Each step up
// is roughly a doubling. The vCPU/memory annotations below are the headline
// figures; disk and bandwidth scale alongside them.
type InstanceType int32

const (
	InstanceType_INSTANCE_TYPE_MICRO InstanceType = 0  // 0.25 vCPU, 128 MiB  -- also the zero/default value
	InstanceType_INSTANCE_TYPE_MILLI InstanceType = 1  // 0.5 vCPU,  256 MiB
	InstanceType_INSTANCE_TYPE_CENTI InstanceType = 2  // 1 vCPU,    512 MiB
	InstanceType_INSTANCE_TYPE_DECI  InstanceType = 3  // 2 vCPU,    1 GiB
	InstanceType_INSTANCE_TYPE_BASE  InstanceType = 4  // 4 vCPU,    2 GiB
	InstanceType_INSTANCE_TYPE_DECA  InstanceType = 5  // 8 vCPU,    4 GiB
	InstanceType_INSTANCE_TYPE_HECTO InstanceType = 6  // 16 vCPU,   8 GiB
	InstanceType_INSTANCE_TYPE_KILO  InstanceType = 7  // 32 vCPU,   16 GiB
	InstanceType_INSTANCE_TYPE_MEGA  InstanceType = 8  // 64 vCPU,   32 GiB
	InstanceType_INSTANCE_TYPE_GIGA  InstanceType = 9  // 128 vCPU,  64 GiB
	InstanceType_INSTANCE_TYPE_TERA  InstanceType = 10 // 256 vCPU,  128 GiB
)

// Enum value maps for InstanceType.
var (
	InstanceType_name = map[int32]string{
		0:  "INSTANCE_TYPE_MICRO",
		1:  "INSTANCE_TYPE_MILLI",
		2:  "INSTANCE_TYPE_CENTI",
		3:  "INSTANCE_TYPE_DECI",
		4:  "INSTANCE_TYPE_BASE",
		5:  "INSTANCE_TYPE_DECA",
		6:  "INSTANCE_TYPE_HECTO",
		7:  "INSTANCE_TYPE_KILO",
		8:  "INSTANCE_TYPE_MEGA",
		9:  "INSTANCE_TYPE_GIGA",
		10: "INSTANCE_TYPE_TERA",
	}
	InstanceType_value = map[string]int32{
		"INSTANCE_TYPE_MICRO": 0,
		"INSTANCE_TYPE_MILLI": 1,
		"INSTANCE_TYPE_CENTI": 2,
		"INSTANCE_TYPE_DECI":  3,
		"INSTANCE_TYPE_BASE":  4,
		"INSTANCE_TYPE_DECA":  5,
		"INSTANCE_TYPE_HECTO": 6,
		"INSTANCE_TYPE_KILO":  7,
		"INSTANCE_TYPE_MEGA":  8,
		"INSTANCE_TYPE_GIGA":  9,
		"INSTANCE_TYPE_TERA":  10,
	}
)

func (x InstanceType) Enum() *InstanceType {
	p := new(InstanceType)
	*p = x
	return p
}

func (x InstanceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InstanceType) Descriptor() protoreflect.EnumDescriptor {
	return file_hyper_proto_enumTypes[0].Descriptor()
}

func (InstanceType) Type() protoreflect.EnumType {
	return &file_hyper_proto_enumTypes[0]
}

func (x InstanceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InstanceType.Descriptor instead.
func (InstanceType) EnumDescriptor() ([]byte, []int) {
	return file_hyper_proto_rawDescGZIP(), []int{0}
}

// Guest CPU architecture. Must match the architecture the image was built for.
type Architecture int32

const (
	Architecture_ARCHITECTURE_X86_64  Architecture = 0 // x86-64 / amd64 -- also the zero/default value
	Architecture_ARCHITECTURE_AARCH64 Architecture = 1 // arm64
)

// Enum value maps for Architecture.
var (
	Architecture_name = map[int32]string{
		0: "ARCHITECTURE_X86_64",
		1: "ARCHITECTURE_AARCH64",
	}
	Architecture_value = map[string]int32{
		"ARCHITECTURE_X86_64":  0,
		"ARCHITECTURE_AARCH64": 1,
	}
)

func (x Architecture) Enum() *Architecture {
	p := new(Architecture)
	*p = x
	return p
}

func (x Architecture) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Architecture) Descriptor() protoreflect.EnumDescriptor {
	return file_hyper_proto_enumTypes[1].Descriptor()
}

func (Architecture) Type() protoreflect.EnumType {
	return &file_hyper_proto_enumTypes[1]
}

func (x Architecture) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Architecture.Descriptor instead.
func (Architecture) EnumDescriptor() ([]byte, []int) {
	return file_hyper_proto_rawDescGZIP(), []int{1}
}

// Request to create and boot a VM.
//
// `instance_type` and `arch` are required by the contract. Note that proto3
// does not enforce field presence: an omitted field decodes to its enum's zero
// value (INSTANCE_TYPE_MICRO / ARCHITECTURE_X86_64), so clients should always
// set them explicitly.
type CreateVmRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The content-addressed id of the image to boot.
	ImgId string `protobuf:"bytes,1,opt,name=img_id,json=imgId,proto3" json:"img_id,omitempty"`
	// Required. The instance size to allocate.
	InstanceType InstanceType `protobuf:"varint,2,opt,name=instance_type,json=instanceType,proto3,enum=hyper.grpc.v0.InstanceType" json:"instance_type,omitempty"`
	// Required. The guest CPU architecture; must match the image.
	Arch Architecture `protobuf:"varint,3,opt,name=arch,proto3,enum=hyper.grpc.v0.Architecture" json:"arch,omitempty"`
	// Optional. Extra kernel command-line arguments. If unset, the server's
	// standard serial-console cmdline is used.
	BootArgs      *string `protobuf:"bytes,4,opt,name=boot_args,json=bootArgs,proto3,oneof" json:"boot_args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVmRequest) Reset() {
	*x = CreateVmRequest{}
	mi := &file_hyper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVmRequest) ProtoMessage() {}

func (x *CreateVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hyper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVmRequest.ProtoReflect.Descriptor instead.
func (*CreateVmRequest) Descriptor() ([]byte, []int) {
	return file_hyper_proto_rawDescGZIP(), []int{0}
}

func (x *CreateVmRequest) GetImgId() string {
	if x != nil {
		return x.ImgId
	}
	return ""
}

func (x *CreateVmRequest) GetInstanceType() InstanceType {
	if x != nil {
		return x.InstanceType
	}
	return InstanceType_INSTANCE_TYPE_MICRO
}

func (x *CreateVmRequest) GetArch() Architecture {
	if x != nil {
		return x.Arch
	}
	return Architecture_ARCHITECTURE_X86_64
}

func (x *CreateVmRequest) GetBootArgs() string {
	if x != nil && x.BootArgs != nil {
		return *x.BootArgs
	}
	return ""
}

// Result of a successful CreateVm.
type CreateVmResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The server-minted id for the new VM; use it in all later RPCs.
	VmId string `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	// The cluster node (Erlang node name) the guest booted on.
	Node          string `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVmResponse) Reset() {
	*x = CreateVmResponse{}
	mi := &file_hyper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVmResponse) ProtoMessage() {}

func (x *CreateVmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hyper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVmResponse.ProtoReflect.Descriptor instead.
func (*CreateVmResponse) Descriptor() ([]byte, []int) {
	return file_hyper_proto_rawDescGZIP(), []int{1}
}

func (x *CreateVmResponse) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *CreateVmResponse) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

// Request to fork a running VM.
type ForkVmRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The id of the parent VM to fork.
	VmId          string `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForkVmRequest) Reset() {
	*x = ForkVmRequest{}
	mi := &file_hyper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForkVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForkVmRequest) ProtoMessage() {}

func (x *ForkVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hyper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForkVmRequest.ProtoReflect.Descriptor instead.
func (*ForkVmRequest) Descriptor() ([]byte, []int) {
	return file_hyper_proto_rawDescGZIP(), []int{2}
}

func (x *ForkVmRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

// Result of a successful ForkVm.
type ForkVmResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The server-minted id for the new child VM; use it in all later RPCs.
	VmId string `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	// The cluster node (Erlang node name) the child booted on.
	Node          string `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForkVmResponse) Reset() {
	*x = ForkVmResponse{}
	mi := &file_hyper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForkVmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForkVmResponse) ProtoMessage() {}

func (x *ForkVmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hyper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForkVmResponse.ProtoReflect.Descriptor instead.
func (*ForkVmResponse) Descriptor() ([]byte, []int) {
	return file_hyper_proto_rawDescGZIP(), []int{3}
}

func (x *ForkVmResponse) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *ForkVmResponse) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

// Request to stop a VM.
type StopVmRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The id of the VM to tear down.
	VmId          string `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopVmRequest) Reset() {
	*x = StopVmRequest{}
	mi := &file_hyper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopVmRequest) ProtoMessage() {}

func (x *StopVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hyper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopVmRequest.ProtoReflect.Descriptor instead.
func (*StopVmRequest) Descriptor() ([]byte, []int) {
	return file_hyper_proto_rawDescGZIP(), []int{4}
}

func (x *StopVmRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

// Request to locate a VM.
type GetVmRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The id of the VM to look up.
	VmId          string `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVmRequest) Reset() {
	*x = GetVmRequest{}
	mi := &file_hyper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVmRequest) ProtoMessage() {}

func (x *GetVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hyper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVmRequest.ProtoReflect.Descriptor instead.
func (*GetVmRequest) Descriptor() ([]byte, []int) {
	return file_hyper_proto_rawDescGZIP(), []int{5}
}

func (x *GetVmRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

// Result of a successful GetVm.
type GetVmResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Echoes the requested id.
	VmId string `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	// The cluster node (Erlang node name) the VM currently runs on.
	Node          string `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVmResponse) Reset() {
	*x = GetVmResponse{}
	mi := &file_hyper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVmResponse) ProtoMessage() {}

func (x *GetVmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hyper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVmResponse.ProtoReflect.Descriptor instead.
func (*GetVmResponse) Descriptor() ([]byte, []int) {
	return file_hyper_proto_rawDescGZIP(), []int{6}
}

func (x *GetVmResponse) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *GetVmResponse) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

// Request a VM's metered compute.
type GetVmUsageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The id of the VM to report on.
	VmId          string `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVmUsageRequest) Reset() {
	*x = GetVmUsageRequest{}
	mi := &file_hyper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVmUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVmUsageRequest) ProtoMessage() {}

func (x *GetVmUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hyper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVmUsageRequest.ProtoReflect.Descriptor instead.
func (*GetVmUsageRequest) Descriptor() ([]byte, []int) {
	return file_hyper_proto_rawDescGZIP(), []int{7}
}

func (x *GetVmUsageRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

// Result of a successful GetVmUsage.
type GetVmUsageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Echoes the requested id.
	VmId string `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	// Cumulative CPU time the VM has actually executed, in microseconds.
	CpuUsec       uint64 `protobuf:"varint,2,opt,name=cpu_usec,json=cpuUsec,proto3" json:"cpu_usec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVmUsageResponse) Reset() {
	*x = GetVmUsageResponse{}
	mi := &file_hyper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVmUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVmUsageResponse) ProtoMessage() {}

func (x *GetVmUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hyper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVmUsageResponse.ProtoReflect.Descriptor instead.
func (*GetVmUsageResponse) Descriptor() ([]byte, []int) {
	return file_hyper_proto_rawDescGZIP(), []int{8}
}

func (x *GetVmUsageResponse) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *GetVmUsageResponse) GetCpuUsec() uint64 {
	if x != nil {
		return x.CpuUsec
	}
	return 0
}

// Result of ListVms.
type ListVmsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Every VM known to the cluster, in no particular order.
	Vms           []*Vm `protobuf:"bytes,1,rep,name=vms,proto3" json:"vms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVmsResponse) Reset() {
	*x = ListVmsResponse{}
	mi := &file_hyper_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVmsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVmsResponse) ProtoMessage() {}

func (x *ListVmsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hyper_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVmsResponse.ProtoReflect.Descriptor instead.
func (*ListVmsResponse) Descriptor() ([]byte, []int) {
	return file_hyper_proto_rawDescGZIP(), []int{9}
}

func (x *ListVmsResponse) GetVms() []*Vm {
	if x != nil {
		return x.Vms
	}
	return nil
}

// A VM and where it runs. Returned by ListVms.
type Vm struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The VM's id.
	VmId string `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	// The cluster node (Erlang node name) the VM runs on.
	Node          string `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vm) Reset() {
	*x = Vm{}
	mi := &file_hyper_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vm) ProtoMessage() {}

func (x *Vm) ProtoReflect() protoreflect.Message {
	mi := &file_hyper_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vm.ProtoReflect.Descriptor instead.
func (*Vm) Descriptor() ([]byte, []int) {
	return file_hyper_proto_rawDescGZIP(), []int{10}
}

func (x *Vm) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *Vm) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

// Request to load an OCI image.
type LoadImageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. An OCI image reference, e.g. "docker.io/library/alpine:3.19".
	ImageRef string `protobuf:"bytes,1,opt,name=image_ref,json=imageRef,proto3" json:"image_ref,omitempty"`
	// Optional. A human-readable label stored with the image (defaults to image_ref).
	Label         *string `protobuf:"bytes,2,opt,name=label,proto3,oneof" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadImageRequest) Reset() {
	*x = LoadImageRequest{}
	mi := &file_hyper_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadImageRequest) ProtoMessage() {}

func (x *LoadImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hyper_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadImageRequest.ProtoReflect.Descriptor instead.
func (*LoadImageRequest) Descriptor() ([]byte, []int) {
	return file_hyper_proto_rawDescGZIP(), []int{11}
}

func (x *LoadImageRequest) GetImageRef() string {
	if x != nil {
		return x.ImageRef
	}
	return ""
}

func (x *LoadImageRequest) GetLabel() string {
	if x != nil && x.Label != nil {
		return *x.Label
	}
	return ""
}

// Result of a successful LoadImage.
type LoadImageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The content-addressed image id; pass it to CreateVm.
	ImgId         string `protobuf:"bytes,1,opt,name=img_id,json=imgId,proto3" json:"img_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadImageResponse) Reset() {
	*x = LoadImageResponse{}
	mi := &file_hyper_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadImageResponse) ProtoMessage() {}

func (x *LoadImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hyper_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadImageResponse.ProtoReflect.Descriptor instead.
func (*LoadImageResponse) Descriptor() ([]byte, []int) {
	return file_hyper_proto_rawDescGZIP(), []int{12}
}

func (x *LoadImageResponse) GetImgId() string {
	if x != nil {
		return x.ImgId
	}
	return ""
}

var File_hyper_proto protoreflect.FileDescriptor

const file_hyper_proto_rawDesc = "" +
	"\n" +
	"\vhyper.proto\x12\rhyper.grpc.v0\x1a\x1bgoogle/protobuf/empty.proto\"\xcb\x01\n" +
	"\x0fCreateVmRequest\x12\x15\n" +
	"\x06img_id\x18\x01 \x01(\tR\x05imgId\x12@\n" +
	"\rinstance_type\x18\x02 \x01(\x0e2\x1b.hyper.grpc.v0.InstanceTypeR\finstanceType\x12/\n" +
	"\x04arch\x18\x03 \x01(\x0e2\x1b.hyper.grpc.v0.ArchitectureR\x04arch\x12 \n" +
	"\tboot_args\x18\x04 \x01(\tH\x00R\bbootArgs\x88\x01\x01B\f\n" +
	"\n" +
	"_boot_args\";\n" +
	"\x10CreateVmResponse\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x12\n" +
	"\x04node\x18\x02 \x01(\tR\x04node\"$\n" +
	"\rForkVmRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"9\n" +
	"\x0eForkVmResponse\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x12\n" +
	"\x04node\x18\x02 \x01(\tR\x04node\"$\n" +
	"\rStopVmRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"#\n" +
	"\fGetVmRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"8\n" +
	"\rGetVmResponse\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x12\n" +
	"\x04node\x18\x02 \x01(\tR\x04node\"(\n" +
	"\x11GetVmUsageRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"D\n" +
	"\x12GetVmUsageResponse\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x19\n" +
	"\bcpu_usec\x18\x02 \x01(\x04R\acpuUsec\"6\n" +
	"\x0fListVmsResponse\x12#\n" +
	"\x03vms\x18\x01 \x03(\v2\x11.hyper.grpc.v0.VmR\x03vms\"-\n" +
	"\x02Vm\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x12\n" +
	"\x04node\x18\x02 \x01(\tR\x04node\"T\n" +
	"\x10LoadImageRequest\x12\x1b\n" +
	"\timage_ref\x18\x01 \x01(\tR\bimageRef\x12\x19\n" +
	"\x05label\x18\x02 \x01(\tH\x00R\x05label\x88\x01\x01B\b\n" +
	"\x06_label\"*\n" +
	"\x11LoadImageResponse\x12\x15\n" +
	"\x06img_id\x18\x01 \x01(\tR\x05imgId*\x9a\x02\n" +
	"\fInstanceType\x12\x17\n" +
	"\x13INSTANCE_TYPE_MICRO\x10\x00\x12\x17\n" +
	"\x13INSTANCE_TYPE_MILLI\x10\x01\x12\x17\n" +
	"\x13INSTANCE_TYPE_CENTI\x10\x02\x12\x16\n" +
	"\x12INSTANCE_TYPE_DECI\x10\x03\x12\x16\n" +
	"\x12INSTANCE_TYPE_BASE\x10\x04\x12\x16\n" +
	"\x12INSTANCE_TYPE_DECA\x10\x05\x12\x17\n" +
	"\x13INSTANCE_TYPE_HECTO\x10\x06\x12\x16\n" +
	"\x12INSTANCE_TYPE_KILO\x10\a\x12\x16\n" +
	"\x12INSTANCE_TYPE_MEGA\x10\b\x12\x16\n" +
	"\x12INSTANCE_TYPE_GIGA\x10\t\x12\x16\n" +
	"\x12INSTANCE_TYPE_TERA\x10\n" +
	"*A\n" +
	"\fArchitecture\x12\x17\n" +
	"\x13ARCHITECTURE_X86_64\x10\x00\x12\x18\n" +
	"\x14ARCHITECTURE_AARCH64\x10\x012\x85\x04\n" +
	"\x05Hyper\x12K\n" +
	"\bCreateVm\x12\x1e.hyper.grpc.v0.CreateVmRequest\x1a\x1f.hyper.grpc.v0.CreateVmResponse\x12E\n" +
	"\x06ForkVm\x12\x1c.hyper.grpc.v0.ForkVmRequest\x1a\x1d.hyper.grpc.v0.ForkVmResponse\x12>\n" +
	"\x06StopVm\x12\x1c.hyper.grpc.v0.StopVmRequest\x1a\x16.google.protobuf.Empty\x12B\n" +
	"\x05GetVm\x12\x1b.hyper.grpc.v0.GetVmRequest\x1a\x1c.hyper.grpc.v0.GetVmResponse\x12Q\n" +
	"\n" +
	"GetVmUsage\x12 .hyper.grpc.v0.GetVmUsageRequest\x1a!.hyper.grpc.v0.GetVmUsageResponse\x12A\n" +
	"\aListVms\x12\x16.google.protobuf.Empty\x1a\x1e.hyper.grpc.v0.ListVmsResponse\x12N\n" +
	"\tLoadImage\x12\x1f.hyper.grpc.v0.LoadImageRequest\x1a .hyper.grpc.v0.LoadImageResponseb\x06proto3"

var (
	file_hyper_proto_rawDescOnce sync.Once
	file_hyper_proto_rawDescData []byte
)

func file_hyper_proto_rawDescGZIP() []byte {
	file_hyper_proto_rawDescOnce.Do(func() {
		file_hyper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hyper_proto_rawDesc), len(file_hyper_proto_rawDesc)))
	})
	return file_hyper_proto_rawDescData
}

var file_hyper_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_hyper_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_hyper_proto_goTypes = []any{
	(InstanceType)(0),          // 0: hyper.grpc.v0.InstanceType
	(Architecture)(0),          // 1: hyper.grpc.v0.Architecture
	(*CreateVmRequest)(nil),    // 2: hyper.grpc.v0.CreateVmRequest
	(*CreateVmResponse)(nil),   // 3: hyper.grpc.v0.CreateVmResponse
	(*ForkVmRequest)(nil),      // 4: hyper.grpc.v0.ForkVmRequest
	(*ForkVmResponse)(nil),     // 5: hyper.grpc.v0.ForkVmResponse
	(*StopVmRequest)(nil),      // 6: hyper.grpc.v0.StopVmRequest
	(*GetVmRequest)(nil),       // 7: hyper.grpc.v0.GetVmRequest
	(*GetVmResponse)(nil),      // 8: hyper.grpc.v0.GetVmResponse
	(*GetVmUsageRequest)(nil),  // 9: hyper.grpc.v0.GetVmUsageRequest
	(*GetVmUsageResponse)(nil), // 10: hyper.grpc.v0.GetVmUsageResponse
	(*ListVmsResponse)(nil),    // 11: hyper.grpc.v0.ListVmsResponse
	(*Vm)(nil),                 // 12: hyper.grpc.v0.Vm
	(*LoadImageRequest)(nil),   // 13: hyper.grpc.v0.LoadImageRequest
	(*LoadImageResponse)(nil),  // 14: hyper.grpc.v0.LoadImageResponse
	(*emptypb.Empty)(nil),      // 15: google.protobuf.Empty
}
var file_hyper_proto_depIdxs = []int32{
	0,  // 0: hyper.grpc.v0.CreateVmRequest.instance_type:type_name -> hyper.grpc.v0.InstanceType
	1,  // 1: hyper.grpc.v0.CreateVmRequest.arch:type_name -> hyper.grpc.v0.Architecture
	12, // 2: hyper.grpc.v0.ListVmsResponse.vms:type_name -> hyper.grpc.v0.Vm
	2,  // 3: hyper.grpc.v0.Hyper.CreateVm:input_type -> hyper.grpc.v0.CreateVmRequest
	4,  // 4: hyper.grpc.v0.Hyper.ForkVm:input_type -> hyper.grpc.v0.ForkVmRequest
	6,  // 5: hyper.grpc.v0.Hyper.StopVm:input_type -> hyper.grpc.v0.StopVmRequest
	7,  // 6: hyper.grpc.v0.Hyper.GetVm:input_type -> hyper.grpc.v0.GetVmRequest
	9,  // 7: hyper.grpc.v0.Hyper.GetVmUsage:input_type -> hyper.grpc.v0.GetVmUsageRequest
	15, // 8: hyper.grpc.v0.Hyper.ListVms:input_type -> google.protobuf.Empty
	13, // 9: hyper.grpc.v0.Hyper.LoadImage:input_type -> hyper.grpc.v0.LoadImageRequest
	3,  // 10: hyper.grpc.v0.Hyper.CreateVm:output_type -> hyper.grpc.v0.CreateVmResponse
	5,  // 11: hyper.grpc.v0.Hyper.ForkVm:output_type -> hyper.grpc.v0.ForkVmResponse
	15, // 12: hyper.grpc.v0.Hyper.StopVm:output_type -> google.protobuf.Empty
	8,  // 13: hyper.grpc.v0.Hyper.GetVm:output_type -> hyper.grpc.v0.GetVmResponse
	10, // 14: hyper.grpc.v0.Hyper.GetVmUsage:output_type -> hyper.grpc.v0.GetVmUsageResponse
	11, // 15: hyper.grpc.v0.Hyper.ListVms:output_type -> hyper.grpc.v0.ListVmsResponse
	14, // 16: hyper.grpc.v0.Hyper.LoadImage:output_type -> hyper.grpc.v0.LoadImageResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_hyper_proto_init() }
func file_hyper_proto_init() {
	if File_hyper_proto != nil {
		return
	}
	file_hyper_proto_msgTypes[0].OneofWrappers = []any{}
	file_hyper_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hyper_proto_rawDesc), len(file_hyper_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hyper_proto_goTypes,
		DependencyIndexes: file_hyper_proto_depIdxs,
		EnumInfos:         file_hyper_proto_enumTypes,
		MessageInfos:      file_hyper_proto_msgTypes,
	}.Build()
	File_hyper_proto = out.File
	file_hyper_proto_goTypes = nil
	file_hyper_proto_depIdxs = nil
}
