// Hyper -- public gRPC interface to a Hyper cluster.
//
// Hyper is a distributed orchestrator for Firecracker microVMs. This file is
// the language-agnostic contract for driving it: creating, stopping, locating,
// and listing microVMs ("VMs") from any gRPC client.
//
// A VM is addressed by its `vm_id` -- a URL-safe base64 string the server mints
// at creation. Placement across the cluster is automatic; the server is
// stateless and identical on every node, so any node can serve any request.
//
// Versioning: this is `v0` and UNSTABLE. The contract may change without notice
// during early development. Pin to a specific commit if you depend on it.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: hyper.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Hyper_CreateVm_FullMethodName   = "/hyper.grpc.v0.Hyper/CreateVm"
	Hyper_ForkVm_FullMethodName     = "/hyper.grpc.v0.Hyper/ForkVm"
	Hyper_StopVm_FullMethodName     = "/hyper.grpc.v0.Hyper/StopVm"
	Hyper_GetVm_FullMethodName      = "/hyper.grpc.v0.Hyper/GetVm"
	Hyper_GetVmUsage_FullMethodName = "/hyper.grpc.v0.Hyper/GetVmUsage"
	Hyper_ListVms_FullMethodName    = "/hyper.grpc.v0.Hyper/ListVms"
	Hyper_LoadImage_FullMethodName  = "/hyper.grpc.v0.Hyper/LoadImage"
)

// HyperClient is the client API for Hyper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The VM lifecycle service.
//
// Errors are returned as standard gRPC statuses (see each RPC). Beyond the ones
// listed, any RPC may return INTERNAL for an unexpected server-side failure.
type HyperClient interface {
	// Create and boot a microVM from an image.
	//
	// The image is scheduled onto the most available node in the cluster
	// (preferring nodes that already hold the image's layers); a per-VM writable
	// root filesystem is built over it and the guest is booted. Returns the
	// minted `vm_id` and the node the guest booted on.
	//
	// Errors:
	//
	//	INVALID_ARGUMENT  -- `img_id` is empty, or an enum field holds an
	//	                    unrecognised value.
	//	RESOURCE_EXHAUSTED -- no node in the cluster has spare capacity.
	//	UNAVAILABLE       -- the VM was placed but its host became unreachable
	//	                    before its id could be confirmed.
	CreateVm(ctx context.Context, in *CreateVmRequest, opts ...grpc.CallOption) (*CreateVmResponse, error)
	// Fork a running microVM: snapshot its disk and boot a colocated child from
	// the copy-on-write clone, falling back to a cluster-wide placement (via a
	// published delta layer) when the parent's node is full. The parent keeps
	// running. The fork is crash-consistent (like a power cut) after a best-effort
	// guest sync. Returns the new child's `vm_id` and the node it booted on.
	//
	// Errors:
	//
	//	NOT_FOUND          -- no VM with this `vm_id` is running in the cluster.
	//	RESOURCE_EXHAUSTED -- no node in the cluster can admit the child.
	//	UNAVAILABLE        -- the parent's host node became unreachable.
	ForkVm(ctx context.Context, in *ForkVmRequest, opts ...grpc.CallOption) (*ForkVmResponse, error)
	// Stop and tear down a running microVM. Idempotent in effect: tearing down a
	// VM that is already stopping is not an error.
	//
	// Errors:
	//
	//	NOT_FOUND   -- no VM with this `vm_id` is running in the cluster.
	//	UNAVAILABLE -- the VM's host node is unreachable.
	StopVm(ctx context.Context, in *StopVmRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Locate a microVM: report the cluster node it currently runs on.
	//
	// Errors:
	//
	//	NOT_FOUND -- no VM with this `vm_id` is known to the cluster.
	GetVm(ctx context.Context, in *GetVmRequest, opts ...grpc.CallOption) (*GetVmResponse, error)
	// Report a microVM's metered compute: the cumulative CPU time it has
	// actually executed, measured from its cgroup. An idle VM accrues (almost)
	// none -- this is compute performed, not compute allocated. Works for
	// stopped VMs too, reporting the recorded lifetime total.
	//
	// Errors:
	//
	//	NOT_FOUND -- no VM with this `vm_id` is running and none was ever metered.
	GetVmUsage(ctx context.Context, in *GetVmUsageRequest, opts ...grpc.CallOption) (*GetVmUsageResponse, error)
	// List every microVM currently known to the cluster, across all nodes.
	ListVms(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListVmsResponse, error)
	// Load an OCI image into the cluster's shared media store and image database.
	//
	// Pulls the referenced image for this node's architecture, flattens it, builds
	// an ext4 rootfs, content-addresses it, and records a base image. Runs on the
	// node that receives the call; the result is visible cluster-wide. Blocks until
	// the load completes -- this can take minutes -- so set a generous deadline.
	// Returns the content-addressed `img_id` to pass to CreateVm.
	//
	// Errors:
	//
	//	INVALID_ARGUMENT    -- `image_ref` is empty or malformed.
	//	FAILED_PRECONDITION -- the node lacks the required tools (skopeo/umoci/mke2fs).
	//	INTERNAL            -- the pull, unpack, build, publish, or DB record failed.
	LoadImage(ctx context.Context, in *LoadImageRequest, opts ...grpc.CallOption) (*LoadImageResponse, error)
}

type hyperClient struct {
	cc grpc.ClientConnInterface
}

func NewHyperClient(cc grpc.ClientConnInterface) HyperClient {
	return &hyperClient{cc}
}

func (c *hyperClient) CreateVm(ctx context.Context, in *CreateVmRequest, opts ...grpc.CallOption) (*CreateVmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateVmResponse)
	err := c.cc.Invoke(ctx, Hyper_CreateVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperClient) ForkVm(ctx context.Context, in *ForkVmRequest, opts ...grpc.CallOption) (*ForkVmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForkVmResponse)
	err := c.cc.Invoke(ctx, Hyper_ForkVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperClient) StopVm(ctx context.Context, in *StopVmRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Hyper_StopVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperClient) GetVm(ctx context.Context, in *GetVmRequest, opts ...grpc.CallOption) (*GetVmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVmResponse)
	err := c.cc.Invoke(ctx, Hyper_GetVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperClient) GetVmUsage(ctx context.Context, in *GetVmUsageRequest, opts ...grpc.CallOption) (*GetVmUsageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVmUsageResponse)
	err := c.cc.Invoke(ctx, Hyper_GetVmUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperClient) ListVms(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListVmsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVmsResponse)
	err := c.cc.Invoke(ctx, Hyper_ListVms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperClient) LoadImage(ctx context.Context, in *LoadImageRequest, opts ...grpc.CallOption) (*LoadImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadImageResponse)
	err := c.cc.Invoke(ctx, Hyper_LoadImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HyperServer is the server API for Hyper service.
// All implementations must embed UnimplementedHyperServer
// for forward compatibility.
//
// The VM lifecycle service.
//
// Errors are returned as standard gRPC statuses (see each RPC). Beyond the ones
// listed, any RPC may return INTERNAL for an unexpected server-side failure.
type HyperServer interface {
	// Create and boot a microVM from an image.
	//
	// The image is scheduled onto the most available node in the cluster
	// (preferring nodes that already hold the image's layers); a per-VM writable
	// root filesystem is built over it and the guest is booted. Returns the
	// minted `vm_id` and the node the guest booted on.
	//
	// Errors:
	//
	//	INVALID_ARGUMENT  -- `img_id` is empty, or an enum field holds an
	//	                    unrecognised value.
	//	RESOURCE_EXHAUSTED -- no node in the cluster has spare capacity.
	//	UNAVAILABLE       -- the VM was placed but its host became unreachable
	//	                    before its id could be confirmed.
	CreateVm(context.Context, *CreateVmRequest) (*CreateVmResponse, error)
	// Fork a running microVM: snapshot its disk and boot a colocated child from
	// the copy-on-write clone, falling back to a cluster-wide placement (via a
	// published delta layer) when the parent's node is full. The parent keeps
	// running. The fork is crash-consistent (like a power cut) after a best-effort
	// guest sync. Returns the new child's `vm_id` and the node it booted on.
	//
	// Errors:
	//
	//	NOT_FOUND          -- no VM with this `vm_id` is running in the cluster.
	//	RESOURCE_EXHAUSTED -- no node in the cluster can admit the child.
	//	UNAVAILABLE        -- the parent's host node became unreachable.
	ForkVm(context.Context, *ForkVmRequest) (*ForkVmResponse, error)
	// Stop and tear down a running microVM. Idempotent in effect: tearing down a
	// VM that is already stopping is not an error.
	//
	// Errors:
	//
	//	NOT_FOUND   -- no VM with this `vm_id` is running in the cluster.
	//	UNAVAILABLE -- the VM's host node is unreachable.
	StopVm(context.Context, *StopVmRequest) (*emptypb.Empty, error)
	// Locate a microVM: report the cluster node it currently runs on.
	//
	// Errors:
	//
	//	NOT_FOUND -- no VM with this `vm_id` is known to the cluster.
	GetVm(context.Context, *GetVmRequest) (*GetVmResponse, error)
	// Report a microVM's metered compute: the cumulative CPU time it has
	// actually executed, measured from its cgroup. An idle VM accrues (almost)
	// none -- this is compute performed, not compute allocated. Works for
	// stopped VMs too, reporting the recorded lifetime total.
	//
	// Errors:
	//
	//	NOT_FOUND -- no VM with this `vm_id` is running and none was ever metered.
	GetVmUsage(context.Context, *GetVmUsageRequest) (*GetVmUsageResponse, error)
	// List every microVM currently known to the cluster, across all nodes.
	ListVms(context.Context, *emptypb.Empty) (*ListVmsResponse, error)
	// Load an OCI image into the cluster's shared media store and image database.
	//
	// Pulls the referenced image for this node's architecture, flattens it, builds
	// an ext4 rootfs, content-addresses it, and records a base image. Runs on the
	// node that receives the call; the result is visible cluster-wide. Blocks until
	// the load completes -- this can take minutes -- so set a generous deadline.
	// Returns the content-addressed `img_id` to pass to CreateVm.
	//
	// Errors:
	//
	//	INVALID_ARGUMENT    -- `image_ref` is empty or malformed.
	//	FAILED_PRECONDITION -- the node lacks the required tools (skopeo/umoci/mke2fs).
	//	INTERNAL            -- the pull, unpack, build, publish, or DB record failed.
	LoadImage(context.Context, *LoadImageRequest) (*LoadImageResponse, error)
	mustEmbedUnimplementedHyperServer()
}

// UnimplementedHyperServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHyperServer struct{}

func (UnimplementedHyperServer) CreateVm(context.Context, *CreateVmRequest) (*CreateVmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVm not implemented")
}
func (UnimplementedHyperServer) ForkVm(context.Context, *ForkVmRequest) (*ForkVmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForkVm not implemented")
}
func (UnimplementedHyperServer) StopVm(context.Context, *StopVmRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method StopVm not implemented")
}
func (UnimplementedHyperServer) GetVm(context.Context, *GetVmRequest) (*GetVmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVm not implemented")
}
func (UnimplementedHyperServer) GetVmUsage(context.Context, *GetVmUsageRequest) (*GetVmUsageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVmUsage not implemented")
}
func (UnimplementedHyperServer) ListVms(context.Context, *emptypb.Empty) (*ListVmsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVms not implemented")
}
func (UnimplementedHyperServer) LoadImage(context.Context, *LoadImageRequest) (*LoadImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadImage not implemented")
}
func (UnimplementedHyperServer) mustEmbedUnimplementedHyperServer() {}
func (UnimplementedHyperServer) testEmbeddedByValue()               {}

// UnsafeHyperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HyperServer will
// result in compilation errors.
type UnsafeHyperServer interface {
	mustEmbedUnimplementedHyperServer()
}

func RegisterHyperServer(s grpc.ServiceRegistrar, srv HyperServer) {
	// If the following call panics, it indicates UnimplementedHyperServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Hyper_ServiceDesc, srv)
}

func _Hyper_CreateVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperServer).CreateVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hyper_CreateVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperServer).CreateVm(ctx, req.(*CreateVmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hyper_ForkVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForkVmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperServer).ForkVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hyper_ForkVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperServer).ForkVm(ctx, req.(*ForkVmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hyper_StopVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopVmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperServer).StopVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hyper_StopVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperServer).StopVm(ctx, req.(*StopVmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hyper_GetVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperServer).GetVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hyper_GetVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperServer).GetVm(ctx, req.(*GetVmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hyper_GetVmUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVmUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperServer).GetVmUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hyper_GetVmUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperServer).GetVmUsage(ctx, req.(*GetVmUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hyper_ListVms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperServer).ListVms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hyper_ListVms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperServer).ListVms(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hyper_LoadImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperServer).LoadImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hyper_LoadImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperServer).LoadImage(ctx, req.(*LoadImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Hyper_ServiceDesc is the grpc.ServiceDesc for Hyper service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Hyper_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hyper.grpc.v0.Hyper",
	HandlerType: (*HyperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVm",
			Handler:    _Hyper_CreateVm_Handler,
		},
		{
			MethodName: "ForkVm",
			Handler:    _Hyper_ForkVm_Handler,
		},
		{
			MethodName: "StopVm",
			Handler:    _Hyper_StopVm_Handler,
		},
		{
			MethodName: "GetVm",
			Handler:    _Hyper_GetVm_Handler,
		},
		{
			MethodName: "GetVmUsage",
			Handler:    _Hyper_GetVmUsage_Handler,
		},
		{
			MethodName: "ListVms",
			Handler:    _Hyper_ListVms_Handler,
		},
		{
			MethodName: "LoadImage",
			Handler:    _Hyper_LoadImage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hyper.proto",
}
