name: forkd-scale-test
on: [push]
jobs:
  job-a:
    runs-on: forkd
    steps:
      - run: echo "scale test A"
      - run: sleep 20
  job-b:
    runs-on: forkd
    steps:
      - run: echo "scale test B"
      - run: sleep 20
  job-c:
    runs-on: forkd
    steps:
      - run: echo "scale test C"
      - run: sleep 20
  job-d:
    runs-on: forkd
    steps:
      - run: echo "scale test D"
      - run: sleep 20
  job-e:
    runs-on: forkd
    steps:
      - run: echo "scale test E"
      - run: sleep 20
